[experiment]
name = "Stage2_Opt_Run1"
output_dir = "sim_out/run_011"

[input]
hic_data = "data/hic_data.dat"

[parallel]
n_workers = 6
runs_per_iter = 5

[optimization]
max_iter = 20
step_start = 1
correction_exponent = 0.8
lambda_alpha_base = 2.0
lambda_alpha0_base = 0.0

[simulation]
N = 65
temperature = 3.0
steps_final = 2_000_000   # 2e6
num_samples = 500
# TF 配置: (TypeA, TypeB)
tf_counts = [40, 8]       
tf_connectivities = [2, 6]

[simulation.physics]
# 基础物理参数
lj_epsilon = 2.1
k_angle = 0.2
lj_range = 65
lj_sigma = 0.5
lj_cutoff = 2.5
r0_bond = 1.4
k_bond = 10.0
De_bond = 20.0
R_wall = 10.0
theta0_angle_pai = 0.5


# Free bead 参数
fbead_r0 = 1.2
fbead_kc = 14.0
Pcutoff_ik = 1.5
free_bead_LJ_epsilon = 0.0

# 接触计算与 Loop 参数
loop_cutoff = 2.0
calc_contact_r0 = 1.6
calc_contact_kc = 4.0

